spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos123456
        group: PX_DEV_GROUP
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8720

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos123456
    group: PX_DEV_GROUP
  config-center:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos123456
    group: PX_DEV_GROUP
  metadata-report:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos123456
    group: PX_DEV_GROUP
