spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos123456
        group: PX_TEST_GROUP

dubbo:
  registry:
    address: nacos://nacos:8848
    username: nacos
    password: nacos123456
    group: PX_TEST_GROUP
  config-center:
    address: nacos://nacos:8848
    username: nacos
    password: nacos123456
    group: PX_TEST_GROUP
  metadata-report:
    address: nacos://nacos:8848
    username: nacos
    password: nacos123456
    group: PX_TEST_GROUP
