server:
  port: 8091
spring:
  application:
    name: px-bff-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos地址
        username: nacos
        password: nacos123456
      config:
        import-check:
          enabled: false
        enabled: false
dubbo:
  application:
    name: px-bff-service
  registry:
    address: nacos://127.0.0.1:8848
    #    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos123456
  consumer:
    timeout: 3000
    retries: 0