server:
  port: 8091
spring:
  application:
    name: px-bff-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}  # Nacos地址
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos123456}
      config:
        import-check:
          enabled: false
        enabled: false
dubbo:
  application:
    name: px-bff-service
  #    serialize-check-status: WARN
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos123456}
  consumer:
    timeout: 3000
    retries: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
