server:
  port: 8091

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: px-bff-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        enabled: false

dubbo:
  application:
    name: px-bff-service
    qos-enable: false
  consumer:
    check: false
    timeout: 3000
    retries: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
