server:
  port: 8081
spring:
  application:
    name: px-app-service  # 服务名，非常重要
  datasource:
    # druid
    #    type: com.alibaba.druid.pool.DruidDataSource
    url: ${DB_URL:jdbc:mysql://localhost:3306/px_site?useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:654321}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:654321}
      database: ${REDIS_DATABASE:0}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}  # Nacos地址
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos123456}
dubbo:
  application:
    name: px-app-service
  #    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://${NACOS_ADDR:127.0.0.1:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos123456}
  provider:
    timeout: 3000

auth:
  jwt:
    secret: 656AQn7q+sHwXzO2yiw2r8Ym7wqiKcoaDHw9HorasU0=

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.px_app_service.domain
