server:
  port: 8080

spring:
  application:
    name: px-gateway

  config:
    import: nacos:px-gateway.yml

  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos123456}
      config:
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos123456}
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      server:
        webflux:
          routes:
            - id: px-bff-service
              uri: lb://px-bff-service
              predicates:
                - Path=/api/frontend/**,/api/backend/**

auth:
  jwt:
    secret: 656AQn7q+sHwXzO2yiw2r8Ym7wqiKcoaDHw9HorasU0=
    white-list:
      - /api/frontend/auth/login
      - /api/frontend/auth/register
      - /api/frontend/app/captcha
      - /api/backend/auth/login
