server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: px-gateway
  cloud:
    nacos:
      config:
        enabled: false
        import-check:
          enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: px-bff-service
              uri: lb://px-bff-service
              predicates:
                - Path=/api/frontend/**,/api/backend/**

auth:
  jwt:
    secret: 656AQn7q+sHwXzO2yiw2r8Ym7wqiKcoaDHw9HorasU0=
    white-list:
      - /api/frontend/auth/login
      - /api/frontend/auth/register
      - /api/frontend/app/captcha
      - /api/backend/auth/login
